[pytest]
DJANGO_SETTINGS_MODULE = pyddns.settings.development
addopts = --ds=pyddns.settings.development
python_files = tests.py test_*.py *_tests.py
env =
    ENABLE_REST_API=1
    DNS_DOMAIN=ddns.example.com
    DNS_HOST=ddns
    DNS_API_PORT=8080
    DNS_SHARED_SECRET=test-shared-secret
    DNS_ALLOW_AGENT=ddclient,DynDNS
    OWN_ADMIN=1
filterwarnings =
    ignore::DeprecationWarning:dns.*
