[pytest]
DJANGO_SETTINGS_MODULE = pyddns.settings.development
addopts = --ds=pyddns.settings.development
python_files = tests.py test_*.py *_tests.py
env =
    ENABLE_REST_API=1
filterwarnings =
    ignore::DeprecationWarning:dns.*
